server:
  port: 8001
#  持久层配置文件

spring:
  data:
    redis:
      host: 10.12.41.201
      password: 123456
      port: 6379
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml


